(function(){
'use strict';
function install(){
  const live=document.getElementById('live');
  if(!live || document.getElementById('xqMaritimeReal')) return;
  const old=document.getElementById('xqMaritimePanel'); if(old) old.remove();
  const style=document.createElement('style');
  style.textContent=`
  #xqMaritimeReal{margin-top:14px}.xq-real-video{position:relative;border:1px solid #1a5b86;border-radius:16px;overflow:hidden;background:#020913;box-shadow:0 20px 70px #0008}.xq-real-video iframe{display:block;width:100%;aspect-ratio:16/9;border:0}.xq-live-overlay{position:absolute;left:12px;top:12px;z-index:2;background:#020a14dd;border:1px solid #2a6f94;border-radius:9px;padding:7px 10px;font:800 10px/1.2 ui-monospace,monospace;color:#fff;backdrop-filter:blur(8px)}.xq-live-dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:#22e6a1;box-shadow:0 0 12px #22e6a1;margin-right:6px}.xq-real-math{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:10px}.xq-real-card{background:#041221;border:1px solid #174d73;border-radius:12px;padding:12px}.xq-real-card small{display:block;color:#80a4c2;font-size:10px}.xq-real-card b{display:block;margin-top:6px;font-size:17px;color:#f2f8ff}.xq-real-formula{margin-top:10px;background:#020b15;border:1px solid #164c72;border-radius:12px;padding:13px;color:#bfe7ff;font:12px/1.7 ui-monospace,SFMono-Regular,Menlo,monospace}.xq-real-controls{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-top:10px}.xq-real-controls input{accent-color:#19a9e8}.xq-real-note{margin-top:9px;color:#7898b3;font-size:10px;line-height:1.55}.xq-real-map{height:155px;margin-top:10px;border:1px solid #164d73;border-radius:12px;overflow:hidden;background:radial-gradient(circle at 20% 70%,#0a4360,#03111e 65%);position:relative}.xq-real-map:before{content:'';position:absolute;inset:0;background-image:linear-gradient(#38b8e518 1px,transparent 1px),linear-gradient(90deg,#38b8e518 1px,transparent 1px);background-size:32px 32px}.xq-real-line{position:absolute;left:12%;right:12%;top:60%;height:2px;background:linear-gradient(90deg,#18e1d4,#2b9bff,#18e1d4);transform:rotate(-10deg);box-shadow:0 0 12px #19cbe0}.xq-real-ship{position:absolute;left:12%;top:53%;font-size:24px;transition:left 1s linear;filter:drop-shadow(0 0 7px #4ddcff)}@media(max-width:800px){.xq-real-math{grid-template-columns:1fr 1fr}}
  `;
  document.head.appendChild(style);
  const panel=document.createElement('section');panel.id='xqMaritimeReal';panel.className='card';
  panel.innerHTML=`<div class="eyebrow">REAL MARITIME MOVEMENT</div><h3 style="margin:7px 0">Live vessel camera + route mathematics</h3><p class="muted tiny" style="margin:0 0 10px">This feed shows an actual maritime camera view — no animated toy ship and no YouTube. The calculation layer below is Xiluqt's route/ETA model.</p><div class="xq-real-video"><div class="xq-live-overlay"><span class="xq-live-dot"></span>REAL-TIME CAMERA · ROTTERDAM WATERWAY</div><iframe src="https://volvevision.com/en/netherlands/south-holland/webcam-nieuwe-waterweg-ship-canal-live-netherlands-cam" title="Real-time Nieuwe Waterweg ship canal webcam" loading="lazy" allow="autoplay;fullscreen;picture-in-picture" allowfullscreen></iframe></div><div class="xq-real-map"><div class="xq-real-line"></div><div id="xqRealShip" class="xq-real-ship">▰</div></div><div class="xq-real-math"><div class="xq-real-card"><small>Route distance</small><b id="xqRD">8,420 km</b></div><div class="xq-real-card"><small>Model vessel speed</small><b id="xqRS">18.0 kn</b></div><div class="xq-real-card"><small>Calculated ETA</small><b id="xqRE">10.53 days</b></div><div class="xq-real-card"><small>Route progress</small><b id="xqRP">0.0%</b></div></div><div class="xq-real-controls"><label class="tiny muted">Speed <input id="xqSpeed" type="range" min="8" max="28" step="0.5" value="18"> <b id="xqSpeedVal">18.0 kn</b></label><label class="tiny muted">Progress <input id="xqProg" type="range" min="0" max="100" step="0.1" value="0"> <b id="xqProgVal">0.0%</b></label></div><div id="xqRF" class="xq-real-formula">ETA = remaining distance ÷ speed = 8,420 km ÷ (18.0 × 1.852 km/h) = 252.7 h ≈ 10.53 days</div><div class="xq-real-note">The camera is a real-world third-party maritime webcam and its availability is controlled by the broadcaster. The route mathematics is a transparent Xiluqt calculation; it is not claiming that the exact vessel visible in the camera is the vessel represented by the route model. For true vessel-specific live ETA, Xiluqt should connect licensed AIS/VDES telemetry.</div><div style="margin-top:10px"><a class="btn secondary" href="https://volvevision.com/en/netherlands/south-holland/webcam-nieuwe-waterweg-ship-canal-live-netherlands-cam" target="_blank" rel="noopener">Open live camera ↗</a></div>`;
  live.appendChild(panel);
  const speed=document.getElementById('xqSpeed'),prog=document.getElementById('xqProg');
  function calc(){const km=8420,kn=+speed.value,p=+prog.value,kmh=kn*1.852,remain=km*(1-p/100),hours=remain/kmh,days=hours/24;document.getElementById('xqRS').textContent=kn.toFixed(1)+' kn';document.getElementById('xqRE').textContent=days.toFixed(2)+' days';document.getElementById('xqRP').textContent=p.toFixed(1)+'%';document.getElementById('xqSpeedVal').textContent=kn.toFixed(1)+' kn';document.getElementById('xqProgVal').textContent=p.toFixed(1)+'%';document.getElementById('xqRF').textContent=`ETA = remaining distance ÷ speed = ${Math.round(remain).toLocaleString()} km ÷ (${kn.toFixed(1)} × 1.852 km/h) = ${hours.toFixed(1)} h ≈ ${days.toFixed(2)} days`;document.getElementById('xqRealShip').style.left=(12+(p*0.76))+'%';}
  speed.addEventListener('input',calc);prog.addEventListener('input',calc);calc();
  setInterval(()=>{const p=+prog.value;prog.value=(p+0.08)%100;calc()},3000);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
