(function(){'use strict';
const VERSION='xiluqt-runtime-v1';
function go(page){const ids=['home','predict','live','api'];if(!ids.includes(page))page='home';document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.getAttribute('data-page')===page));try{history.replaceState(null,'','#'+page)}catch(e){}window.scrollTo({top:0,behavior:'smooth'});}
function nav(){document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b){e.preventDefault();e.stopPropagation();go(b.getAttribute('data-page'));}},true);const h=location.hash.replace('#','');if(['home','predict','live','api'].includes(h))go(h);window.XiluqtNavigate=go;}
function api(){const b=document.getElementById('apiRun');if(b){b.onclick=function(e){e.preventDefault();const out=document.getElementById('apiOut');const status=document.getElementById('apiStatus');if(status)status.textContent='BETA · DEPLOYMENT PROTOCOL';if(out){out.textContent=JSON.stringify({status:'beta',protocol:'XILUQT-API-BETA',message:'Prediction endpoint is under deployment; this prototype is for evaluation and integration testing.',timestamp:new Date().toISOString()},null,2)}try{window.XiluqtBrain&&window.XiluqtBrain.render&&window.XiluqtBrain.render()}catch(err){}}}}
function brand(){document.querySelectorAll('.xlogo').forEach(x=>{if(!x.querySelector('img'))x.innerHTML='<img src="./xiluqt-x.svg?v=1" alt="Xiluqt X" style="width:100%;height:100%;object-fit:contain;display:block">';x.style.overflow='hidden'});if(!document.querySelector('link[data-xiluqt-icon]')){document.head.insertAdjacentHTML('beforeend','<link data-xiluqt-icon rel="apple-touch-icon" sizes="180x180" href="./xiluqt-icon-180.png?v=1"><link data-xiluqt-icon rel="icon" type="image/png" sizes="512x512" href="./xiluqt-icon-512.png?v=1">')}}
function status(){if(document.querySelector('.xq-beta-banner'))return;const m=document.querySelector('.main');if(!m)return;const el=document.createElement('div');el.className='xq-beta-banner';el.innerHTML='<span class="xq-bdot"></span><b>XILUQT BETA</b><span>API DEPLOYMENT PROTOCOL · Prototype environment · Live signals are contextual, not production guarantees</span>';m.prepend(el);const s=document.createElement('style');s.textContent='.xq-beta-banner{display:flex;align-items:center;gap:8px;margin:2px 0 12px;padding:8px 11px;border:1px solid #15518a;border-radius:10px;background:#041426;color:#83a6c7;font-size:10px;letter-spacing:.2px}.xq-beta-banner b{color:#21e8e0;font-size:9px;letter-spacing:1px}.xq-bdot{width:6px;height:6px;border-radius:50%;background:#ffae37;box-shadow:0 0 10px #ffae37;flex:none}';document.head.appendChild(s)}
function boot(){brand();status();nav();api();setTimeout(()=>{brand();status();api()},250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.XiluqtRuntime={version:VERSION,go};
})();
