const state={components:[],products:new Set(),source:'Built-in intelligence dataset'};
const demo=[{part:'MEM-AX19',manufacturer:'Aster Memory',product:'Edge Controller X1',lifecycle:'NRND',lead:13,sources:1,geo:3,alt:3},{part:'PMIC-T48',manufacturer:'Tera Power',product:'Edge Controller X1',lifecycle:'Active',lead:8,sources:2,geo:2,alt:4},{part:'MCU-H743',manufacturer:'Horizon Micro',product:'Gateway G2',lifecycle:'Active',lead:6,sources:3,geo:1,alt:5},{part:'CAN-FD9',manufacturer:'Nexa Logic',product:'Gateway G2',lifecycle:'Active',lead:5,sources:4,geo:1,alt:6}];
const $=s=>document.querySelector(s);
function risk(c){let score=0;score+=c.lifecycle==='Obsolete'?45:c.lifecycle==='EOL'?35:c.lifecycle==='NRND'?22:5;score+=Math.max(0,18-c.lead*1.1);score+=(c.sources<=1?25:c.sources===2?13:4);score+=c.geo*4;return Math.min(100,Math.round(score))}
function level(n){return n>=65?'high':n>=40?'medium':'low'}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function render(){const cs=state.components;$('#metricComponents').textContent=cs.length;$('#metricProducts').textContent=state.products.size;const risks=cs.map(risk);const avg=risks.length?Math.round(risks.reduce((a,b)=>a+b,0)/risks.length):0;$('#metricRisk').textContent=avg;$('#metricAlternatives').textContent=cs.reduce((a,c)=>a+(c.alt||0),0);$('#componentList').innerHTML=cs.length?cs.map(c=>{const r=risk(c);return `<div class="component-row"><b>${esc(c.part)}</b><span>${esc(c.manufacturer||'Unknown')}</span><span>${esc(c.product||'Unassigned')}</span><span class="risk ${level(r)}">${level(r).toUpperCase()} · ${r}</span></div>`}).join(''):`<div class="muted" style="padding:25px">No components yet. Load a BOM or reset to the built-in dataset.</div>`;const top=[...cs].sort((a,b)=>risk(b)-risk(a))[0];if(top){$('#graphChip').textContent=top.part;$('#graphComponent').textContent=top.part;$('#graphSupplier').textContent=top.manufacturer||'Unknown';$('#graphProduct').textContent=top.product||'Unassigned';$('#graphSummary').textContent=`Highest calculated exposure: ${top.part} · ${risk(top)}/100 risk · ${top.product||'product unassigned'}.`}}
function parseCSV(text){const lines=text.trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const h=lines[0].split(',').map(x=>x.trim().toLowerCase());return lines.slice(1).map(line=>{const v=line.split(',').map(x=>x.trim());const o={};h.forEach((k,i)=>o[k]=v[i]||'');return {part:o.part||o.part_number||o.component||o.mpn||'UNKNOWN',manufacturer:o.manufacturer||o.vendor||'',product:o.product||o.product_name||o.program||'Unassigned',lifecycle:o.lifecycle||'Active',lead:Number(o.lead_time||o.lead||8),sources:Number(o.suppliers||o.sources||1),geo:Number(o.geopolitical_exposure||o.geo||1),alt:Number(o.alternatives||0)}})}
function load(cs,source){state.components=cs;state.products=new Set(cs.map(c=>c.product).filter(Boolean));state.source=source;render();$('#fileStatus').textContent=`${cs.length} component rows loaded · ${source}`;localStorage.setItem('xiluqt-bom',JSON.stringify(cs));}
function answer(q){const cs=state.components;if(!cs.length)return 'There is no BOM in the workspace yet. Load a BOM first so the intelligence engine has evidence to reason over.';const top=[...cs].sort((a,b)=>risk(b)-risk(a))[0];if(/qualify|first/i.test(q))return `${top.part} should be qualified first. Its calculated risk is ${risk(top)}/100, driven by ${top.lifecycle.toLowerCase()} lifecycle posture, ${top.sources} known source${top.sources===1?'':'s'}, ${top.lead}-day lead time and downstream exposure in ${top.product}. Recommendation: qualify an alternate and validate it against the product's electrical and firmware constraints.`;if(/product.*exposed|exposed.*product/i.test(q)){const counts={};cs.forEach(c=>counts[c.product]=(counts[c.product]||0)+risk(c));const p=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];return `${p[0]} currently has the highest aggregate component-risk exposure in this BOM. The score is a prioritisation signal, not a forecast of guaranteed loss. Review its highest-risk dependencies before the next procurement cycle.`}if(/unavailable|break|impact/i.test(q))return `If ${top.part} becomes unavailable, the immediate concern is ${top.product}. The engine flags the dependency because its current risk score is ${risk(top)}/100. The correct next step is to qualify a technically compatible alternative, then model the substitution across affected products before changing production sourcing.`;return `For this BOM, ${top.part} is the highest-risk dependency at ${risk(top)}/100. Ask about qualification priority, product exposure, or an availability scenario for a more specific analysis.`}
function bind(){const input=$('#bomFile');$('#chooseFile').onclick=()=>input.click();input.onchange=()=>input.files[0]&&readFile(input.files[0]);const dz=$('#dropzone');['dragenter','dragover'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f)readFile(f)});$('#resetData').onclick=()=>load(demo,'Built-in dataset');$('#askForm').onsubmit=e=>{e.preventDefault();const q=$('#question').value.trim();if(!q)return;$('#answer').innerHTML=`<span class="answer-label">XILUQT INTELLIGENCE</span><p>${esc(answer(q))}</p>`};document.querySelectorAll('.suggestions button').forEach(b=>b.onclick=()=>{$('#question').value=b.dataset.q;$('#askForm').requestSubmit()});let saved=null;try{saved=JSON.parse(localStorage.getItem('xiluqt-bom')||'null')}catch{}load(Array.isArray(saved)&&saved.length?saved:demo,saved?'Saved workspace':'Built-in dataset')}
function readFile(f){const r=new FileReader();r.onload=()=>load(parseCSV(String(r.result)),`Customer BOM · ${f.name}`);r.readAsText(f)}
function intro(){document.querySelectorAll('.hero,.signal-grid,.section').forEach((el,i)=>{el.style.opacity='0';el.style.transform='translateY(16px)';el.style.transition=`opacity .7s ${i*70}ms,transform .7s ${i*70}ms`;requestAnimationFrame(()=>{el.style.opacity='1';el.style.transform='translateY(0)'})})}
window.addEventListener('DOMContentLoaded',()=>{bind();intro()});