const demo=[{part:'MEM-AX19',manufacturer:'Aster Memory',product:'Edge Controller X1',lifecycle:'NRND',lead:13,sources:1},{part:'PMIC-T48',manufacturer:'Tera Power',product:'Edge Controller X1',lifecycle:'Active',lead:8,sources:2},{part:'MCU-H743',manufacturer:'Horizon Micro',product:'Gateway G2',lifecycle:'Active',lead:6,sources:3}];
const state={components:demo};
const $=s=>document.querySelector(s);
const score=c=>Math.min(100,Math.round((c.lifecycle==='NRND'?30:8)+Math.max(0,20-c.lead)+(c.sources===1?28:c.sources===2?14:5)));
const level=n=>n>=65?'high':n>=40?'medium':'low';
const esc=x=>String(x??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
function render(){const cs=state.components,products=new Set(cs.map(c=>c.product).filter(Boolean)),rs=cs.map(score);$('#mComponents').textContent=cs.length;$('#mProducts').textContent=products.size;$('#mRisk').textContent=rs.length?Math.round(rs.reduce((a,b)=>a+b,0)/rs.length):0;$('#mAlternatives').textContent=cs.length*3;$('#rows').innerHTML=cs.map(c=>{const r=score(c);return `<div class="row"><b>${esc(c.part)}</b><span>${esc(c.manufacturer)}</span><span>${esc(c.product)}</span><span class="risk ${level(r)}">${level(r).toUpperCase()} · ${r}</span></div>`}).join('');const t=[...cs].sort((a,b)=>score(b)-score(a))[0];if(t){$('#gChip').textContent=t.part;$('#gComp').textContent=t.part;$('#gSupplier').textContent=t.manufacturer;$('#gProduct').textContent=t.product;$('#gNote').textContent=`Highest calculated dependency risk: ${t.part} · ${score(t)}/100.`}}
function parseCSV(text){const lines=text.trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const h=lines[0].split(',').map(x=>x.trim().toLowerCase());return lines.slice(1).map(line=>{const v=line.split(',').map(x=>x.trim()),o={};h.forEach((k,i)=>o[k]=v[i]||'');return{part:o.part||o.part_number||o.mpn||'UNKNOWN',manufacturer:o.manufacturer||o.vendor||'Unknown',product:o.product||o.product_name||'Unassigned',lifecycle:o.lifecycle||'Active',lead:+(o.lead_time||o.lead||8),sources:+(o.suppliers||o.sources||1)}})}
function load(cs,label){state.components=cs;render();$('#fileState').textContent=`${cs.length} rows · ${label}`}
function readFile(f){const r=new FileReader();r.onload=()=>load(parseCSV(String(r.result)),`Customer BOM · ${f.name}`);r.readAsText(f)}
function analyze(q){if(!state.components.length)return'Load a BOM first.';const t=[...state.components].sort((a,b)=>score(b)-score(a))[0];if(/qualify|first/i.test(q))return`${t.part} should be qualified first. Calculated risk: ${score(t)}/100. Signals: ${t.lifecycle.toLowerCase()} lifecycle posture, ${t.sources} source${t.sources===1?'':'s'} and ${t.lead}-day lead time. Recommendation: qualify a technically compatible alternate.`;if(/product|exposed/i.test(q))return`${t.product} has the highest-priority dependency because ${t.part} carries the highest calculated risk.`;return`Highest-risk dependency: ${t.part} at ${score(t)}/100, affecting ${t.product}.`}
window.addEventListener('DOMContentLoaded',()=>{render();$('#choose').onclick=()=>$('#file').click();$('#file').onchange=()=>$('#file').files[0]&&readFile($('#file').files[0]);$('#reset').onclick=()=>load(demo,'Built-in dataset');$('#form').onsubmit=e=>{e.preventDefault();$('#answer').textContent=analyze($('#q').value)};document.querySelectorAll('.chips button').forEach(b=>b.onclick=()=>{$('#q').value=b.dataset.q;$('#form').requestSubmit()});const d=$('#drop');d.ondragover=e=>{e.preventDefault();d.classList.add('drag')};d.ondragleave=()=>d.classList.remove('drag');d.ondrop=e=>{e.preventDefault();d.classList.remove('drag');if(e.dataTransfer.files[0])readFile(e.dataTransfer.files[0])}});